### ISSUE TITLE
Syntax Error while running fauxmo

### ISSUE THREAD

**Issue by saurabh500** [n8henrie/fauxmo#28]
- **Operating system and version**: Raspberry Pi Rasbian Jessie
- **Python version**: 3.4.2
- **Fauxmo version** (`fauxmo --help`): Not able to retrieve the version

## My Issue
I tried to install and run fauxmo using the instructions at README [https://github.com/n8henrie/fauxmo#simple-install-from-pypi]

```
Traceback (most recent call last):
  File "/home/pi/venv/bin/fauxmo", line 7, in <module>
    from fauxmo.cli import cli
  File "/home/pi/venv/lib/python3.4/site-packages/fauxmo/cli.py", line 10, in <module>
    from fauxmo.fauxmo import main
  File "/home/pi/venv/lib/python3.4/site-packages/fauxmo/fauxmo.py", line 37
    logger.info(f"Fauxmo version {__version__}")
                                              ^
SyntaxError: invalid syntax
```
Are there any python dependencies not satisfied here? 

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues

**Comment by n8henrie** [comment]
If you're installing from pip without specifying a version you will be
getting >=0.4.0, which requires 3.6 (which provides the f-strings that are
causing the syntax error). I have this spelled out in the issue template
and the readme, but you couldn't have known easily since it won't even
print the version for you.

If you're stuck with this version of python, you might try `pip install
fauxmo<0.3.0`, though if you can upgrade to 3.6 I highly recommend it.

You're right, I should try to change this so the version string still works
in prior versions, thanks for the bug report.

**Comment by saurabh500** [comment]
Thanks @n8henrie 
When I try to use fauxmo<0.3.0 I could successfully use `fauxmo --help`
I added the sample config from the repo and tried launching `fauxmo -c config.json` 

However I get another error 

```
Traceback (most recent call last):
  File "/home/pi/venv/bin/fauxmo", line 11, in <module>
    sys.exit(cli())
  File "/home/pi/venv/lib/python3.4/site-packages/fauxmo/cli.py", line 27, in cli
    main(config_path=args.config, verbosity=verbosity)
  File "/home/pi/venv/lib/python3.4/site-packages/fauxmo/fauxmo.py", line 159, in main
    for device in config.get('DEVICES'):
TypeError: 'NoneType' object is not iterable
```

Any idea what is going on with the config format? My config is the same as the config here https://github.com/n8henrie/fauxmo/blob/master/config-sample.json#L27

**Comment by n8henrie** [comment]
I'm not at home to verify, but I presume it's because that's the config for
the current version of fauxmo, which changed recently (I think with v0.4.0).

Go back to the "releases" link in GitHub and follow the link for the
version you're using to find the config example for that release.

**Comment by n8henrie** [comment]
Here's a [direct link to the config sample for <3.0](https://github.com/n8henrie/fauxmo/blob/d877c513ad45cbbbd77b1b83e7a2f03bf0004856/config-sample.json).

**Comment by n8henrie** [comment]
Unfortunately my attempted fix does *not* solve the issue of a `SyntaxError` (and not printing the Fauxmo version) when installed under the wrong python version, since the module is imported in the CLI script.

Instead of a more complicated workaround, I've added the new [`python_requires` keyword](http://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords) to `setup.py`, so that people using pip >= 9.0.1 should get an error on attempted install.

Unfortunately folks using older versions of pip will still run into this issue, so I added a note to the README to update pip prior to installation.
