### ISSUE TITLE
Install Failure on Raspberry Pi 3

### ISSUE THREAD

**Issue by REHolt** [n8henrie/fauxmo#8]
- **Raspian Kernal 4.4 May 2016**:
- **Python 3.4.2**:
- **Fauxmo version V0.3.2**:

## My Issue: trying to install Fauxmo on a Raspberry Pi 3 and I am getting an install error

Error: Command '['/home/pi/fauxmo/venv/bin/python3, , '-| m, 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

I'm fairly new to Raspberry Pi, is this a version error? Not sure what to do here?

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [x] Include the Python and Fauxmo version in your issue
- [x] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Search the existing (and closed) issues

**Comment by n8henrie** [comment]
Can you tell me what command you're running?

**Comment by REHolt** [comment]
Straight from the direction.

git clone https://github.com/n8henrie/fauxmo.git
cd fauxmo
python3 -m venv venv

I also tried running the setup.Ph.

**Comment by n8henrie** [comment]
I'm having trouble reproducing the error. What version of Raspbian are you using? I assume Jessie based on the python version.

Do you have `python3.4-venv` installed? I can't remember if that comes by default. 

To check: `sudo dpkg --get-selections | grep python3.4-venv` <- Should show up with `install` next to it.

If not: `sudo apt-get install python3.4-venv` and try again. If this fixes the issue I'll add it to the README.

If not, can you include the output of `uname -a`?

**Comment by REHolt** [comment]
I'll give it a try when I get home. My internet has been down since early am yesterday, so haven't done much since I first posted.

Thanks for the reply.

**Comment by REHolt** [comment]
that did seem to fix things. it is now installing.

**Comment by REHolt** [comment]
Not sure i fully understand what should be edited in the config.jason file other than the ip address.

**Comment by REHolt** [comment]
Install resulted in the following errors:

Installing collected packages: fauxmo, homeassistant, requests, jinja2, pytz, pyyaml, pip, vincenty, MarkupSafe
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 214, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 204, in clobber
    os.makedirs(destdir)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/fauxmo'

Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by REHolt** [comment]
OK, I re-ran the install with :sudo" and it seemed to complete. I appears to be running, but ECHO doesn't "Discover" any devices.

**Comment by REHolt** [comment]
I'm not clear; is the HAP module also running on the same RasPi? if so, should i change the IP address in that section as well?

**Comment by n8henrie** [comment]
In general, while it *works*, you shouldn't need to use `sudo` -- you should install into a virtualenv or use the `--user` flag for `pip` to install into a directory you have permissions for.

> I'm not clear; is the HAP module also running on the same RasPi? if so, should i change the IP address in that section as well?

What HAP module are you talking about? Did you mean Home Assistant (hass)?

You seem to be jumping ahead of yourself a bit here.

1. Figure out what devices you can access with either Home Assistant or via some kind of http request.
1. Use [`config-sample.json`](https://github.com/n8henrie/fauxmo/blob/master/config-sample.json) to built your own `config.json` using information from step 1.
1. Run Fauxmo in debug mode to ensure your devices are being presented to the Echo.
1. Discover devices with the Echo.

I'm going to go ahead and close this issue, as the installation failure is resolved. If you're still having trouble, I encourage you to open a new issue -- in order to help save everyone time and effort, I request that you follow the issue template (including "what have you tried," a more thorough description of your issue, your full environment, whether you've found any relevant information in the existing issues, etc.).
