### ISSUE TITLE
3.7.3 installed, but not running unless explicitly called - how to remove 3.5.3?

### ISSUE THREAD

**Issue by johngo7470** [n8henrie/fauxmo#83]
- Issues not following the template may be closed for that reason alone.
- **Operating system and version**: Raspian
- **Python version**: all of the above
- **Fauxmo version** (`fauxmo --version`): 0.4.9
- **Echo device type** (e.g. Echo, Echo Plus, Dot): n/a 
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**:  n/a

On my Raspberry, I have python 2.7.13, 3.5.3, and sorta have 3.7.3:

pi@raspi:/etc/systemd/system $ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
pi@raspi:/etc/systemd/system $ python --version
**Python 2.7.13**

pi@raspi:/etc/systemd/system $ python3
**Python 3.5.3** (default, Sep 27 2018, 17:25:39)

pi@raspi:/etc/systemd/system $ python3.7
**pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.3**

Apparently, in removing 3.5.3, I have bungled everything that relied on it (such as lirc).

pyenv wasn't used to install 3.5.3 - I'm guessing apt-get was, or it was part of the native installation. 

Do you have any information on how one can safely remove (or displace) an earlier version of python, to be able to use fauxmo, withouth needing to specify the full path?  (e.g. /opt/pyenv/versions/3.7.3/bin/fauxmo -c /home/pi/config.json)

(this is why I'm cautious of venv - not always clear what I'm getting and from where)

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by johngo7470** [comment]
Somehow I was able to get it working from systemd, while python3.5 is installed... not sure how, but systemd is now calling fauxmo in the python directory (non-venv), and it's working. I'll close this as an exercise for the student...

**Comment by n8henrie** [comment]
> (this is why I'm cautious of venv - not always clear what I'm getting and from where)

I think you're confusing [pyenv](https://github.com/pyenv/pyenv/) and [venv](https://docs.python.org/3/library/venv.html) (sometimes referred to as `pyvenv`, related to its predecessor `pyvirtualenv`). Very important leading `v`.

> Do you have any information on how one can safely remove (or displace) an earlier version of python, to be able to use fauxmo, withouth needing to specify the full path? (e.g. /opt/pyenv/versions/3.7.3/bin/fauxmo -c /home/pi/config.json)

pyenv will automatically use whatever version of python that you tell it to, either with e.g. `pyenv global 3.7.3`, or for the current directory (and its subdirectories IIRC) with `pyenv local 3.7.3`, which will create a `.python-version` file, or just for the current session with `pyenv shell 3.7.3`.

venv, on the other hand, makes a "virtual environment" to keep one project's dependencies from polluting your system python installation or other projects. Because Fauxmo has no dependencies this may not be necessary, but is generally a good practice.

For interactive use, I usually have `.python-version` files in my projects that pyenv will use to automatically use the right **version** of python, and to alert users about the same.

```console
$ cd MY_PROJECT_NAME_HERE
$ pyenv local 3.7.3 # tell pyenv to set the python version for this project
$ python3 -m venv .venv # create a virtual environment named .venv linked to this python version
$ source ./.venv/bin/activate # activate the current virtual environment so installed dependencies all go into this venv
$ # develop...
```

Then, once I want to put that script into a cron job / systemd script / something else, I tend to be as explicit as possible and use the full path through the virtualenv (which ensures that the right environment is used for running the script), e.g. `ExecStart=/home/n8henrie/MY_PROJECT_NAME_HERE/.venv/bin/python -m mymodule`.

Hope that makes sense.
