### ISSUE TITLE
dimmer emulation

### ISSUE THREAD

**Issue by rudiratlos** [n8henrie/fauxmo#91]
thanks for your valuable work. works great.
is it possible to setup a dimmer switch like:
alexa, set kitchen light to 75%

**Comment by n8henrie** [comment]
Not currently.

It looks like it may be possible to figure out: https://github.com/openhab/openhab2-addons/issues/4808, but since I don't have a wemo dimmer to tinker with, I won't be able to implement it.

I'll leave the issue open for another week or two to see if there are any volunteers to try to implement, if no takers will plan to close.

**Comment by n8henrie** [comment]
I haven't gotten a reply, so I'm closing this issue as dead. Please feel free to let me know if I should re-open.
