### ISSUE TITLE
Using Fauxmo to control GPIO Relay board

### ISSUE THREAD

**Issue by Isarian-de-Picardia** [n8henrie/fauxmo#95]
- Issues not following the template may be closed for that reason alone.
- **Operating system and version**: Raspberry Pi, Raspbian  v10 Buster
- **Python version**: 3.7.3
- **Fauxmo version** (`fauxmo --version`): v0.5.0
- **Echo device type** (e.g. Echo, Echo Plus, Dot): Echo Dot 3rd Gen
- **[Echo Firmware Version](https://github.com/n8henrie/fauxmo/blob/dev/README.md#troubleshooting--faq)**:  3658075268 

## My Issue
I was watching the video here: https://www.youtube.com/watch?v=OQyntQLazMU

This video uses a collection of Python scripts that can be seen here: https://github.com/skiwithpete/relaypi/tree/master/4port

The scripts work fine on their own, but have to be run individually.

Relay 1 plugged into the Raspberry Pi GPIO here: https://i.imgur.com/AlIoygH.png

I was wondering how Fauxmo could be combined with these GPOI scripts to control the relay board with the Echo Dot. Say have each relay register as a Switch on Alexa, then have the on/off state controlled by running script similar to 5a and 5b in that collection for Relay2.

## [WHYT](http://mattgemmell.com/what-have-you-tried)

---

Please make sure you've taken these steps before submitting a new issue:

- [ ] Try to reproduce the issue with Fauxmo installed in a
  [venv](https://docs.python.org/3/library/venv.html)
- [ ] Ensure you're running a supported version of Python
    - Requires Python >= 3.2 for Fauxmo < 0.3.0
    - Requires Python >= 3.4.4 for Fauxmo >= 0.3.0
    - Requires Python >= 3.6.0 for Fauxmo >= 0.4.0
- [ ] Run Fauxmo in debug mode (`-vvv`) and include relevant output
- [ ] Include your Fauxmo `config.json`
- [ ] Search the existing (including closed) issues
- [ ] Please use [codeblocks][1] around your debug output and config

[1]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by n8henrie** [comment]
Hi!

This should be pretty easy. I would recommend starting with the [docs for CommandLinePlugin][0] (note that I just had to rebuild the docs, which hadn't updated with the last major version for some reason). Also please disregard the part about it not being included by default, which is a recent change. I have updated this docstring in the dev branch.

Basically, if you can turn on switch with `python scripty1.py` and off with `python script2.py`, you should be able to configure a CommandLinePlugin instance to run `/path/to/python /path/to/script1.py` as the `on_cmd` and analogously for the `off_cmd`.

Alternatively, since the scripts you're referring to are in Python, you could also subclass `FauxmoPlugin` and have the switch logic embedded into a custom class; for further details check out [n8henrie/fauxmo-plugins](https://github.com/n8henrie/fauxmo-plugins).

[0]: https://fauxmo.readthedocs.io/en/latest/fauxmo.plugins.html#module-fauxmo.plugins.commandlineplugin

**Comment by n8henrie** [comment]
Bump.

This issue is pending a response and is blocked until I have more info. To keep the issue list groomed, I will often close these stalled issues if they go a prolonged time without a response. In this case, I will give it another week or so.
